### ISSUE TITLE
apisix on lua5.3

### ISSUE THREAD

**Issue by Fuchange** [api7/build-tools#6]
Hello， I would like to ask whether apifix has plans based on lua5.3 now?

I'm now trying to get apifix to work in lua5.3, but I'm having some problems.

If there are relevant documents, it will provide a lot of help.

你好， 我想问一下现在有计划将apisix基于lua5.3运行吗？ 

我正在尝试做这个，但遇到了一些困难。

如果有相关的文档的话将会很有帮助。

@idbeta

**Comment by idbeta** [comment]
@membphis Please move this issue to the [apisix github repository](https://github.com/apache/apisix), and answer this question when you have time.

**Comment by moonming** [comment]
No, apisix is based on openresty,which is only support luajit now
